// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaB-O6DUDlFydZ2fTPZ9Of_65absVATs',
    appId: '1:927301585971:web:d22b4b8aec13e1deada746',
    messagingSenderId: '927301585971',
    projectId: 'blog-app-notifications',
    authDomain: 'blog-app-notifications.firebaseapp.com',
    storageBucket: 'blog-app-notifications.firebasestorage.app',
    measurementId: 'G-3LVGP0M9RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbd_tppuBMWmweb17vdqtPifMPnUtsMGs',
    appId: '1:927301585971:android:5d95d5a96fd96c1eada746',
    messagingSenderId: '927301585971',
    projectId: 'blog-app-notifications',
    storageBucket: 'blog-app-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxr1mrrYTbTlFEIsfuSOhA1VkKxxpxRO8',
    appId: '1:927301585971:ios:ba8d329abcf6eed2ada746',
    messagingSenderId: '927301585971',
    projectId: 'blog-app-notifications',
    storageBucket: 'blog-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxr1mrrYTbTlFEIsfuSOhA1VkKxxpxRO8',
    appId: '1:927301585971:ios:ba8d329abcf6eed2ada746',
    messagingSenderId: '927301585971',
    projectId: 'blog-app-notifications',
    storageBucket: 'blog-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaB-O6DUDlFydZ2fTPZ9Of_65absVATs',
    appId: '1:927301585971:web:340aed5e650137b7ada746',
    messagingSenderId: '927301585971',
    projectId: 'blog-app-notifications',
    authDomain: 'blog-app-notifications.firebaseapp.com',
    storageBucket: 'blog-app-notifications.firebasestorage.app',
    measurementId: 'G-DCY3T8YBHM',
  );
}
